### ISSUE TITLE
Move this repo to the LSE-Methodology organization

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/coursepack-bookdown#21]
@amatsuo could you move this to the LSE-Methodology organization? This will involve some YAML changes and maybe a few other configuration changes. 

Since we started this, it's become possible to publish from a designated sub directory, making the use of the `gh-pages` branch unnecessary. Might be worth using that structure.

Thanks!

**Comment by chmue** [comment]
Maybe it's easier to just merge the changes in the fork and then transfer ownership?

Edit: Ah no, sorry! I should have read until the very end of the page. You want to make the repo public and then delete it right after that such that the private fork gets its own history tree.

**Comment by chmue** [comment]
I think it worked! The other repo is not a fork anymore. 

The issues seem to be missing but I am not sure if you have to add an issue tracker separately. We might need to copy over the issues from here by hand. I'm happy to look into this if you give me full access to the other repo.

**Comment by kbenoit** [comment]
Done.

**Comment by chmue** [comment]
Could you also make me an owner of this repo, @kbenoit ? I am using [this tool](https://github-issue-mover.appspot.com/) to move the issues. It tells me that I have the required access to LSE-Methodology/MY451 but not for this repo.

**Comment by kbenoit** [comment]
You have admin rights, but LSE-Methodology is the "owner". If I transfer ownership then it moves to your account.

<img width="937" alt="screenshot 2017-09-27 13 56 03" src="https://user-images.githubusercontent.com/2182246/30914495-c62e8cac-a38b-11e7-8910-274e3e36a499.png">

**Comment by chmue** [comment]
Ok. I *do* have the right access for `LSE-Methodology/MY451`. But I don't have the right access to this repo `kbenoit/coursepack-bookdown`.

**Comment by kbenoit** [comment]
See Slack on the brexit team

**Comment by kbenoit** [comment]
This issue was moved to LSE-Methodology/MY451#2
